Set message

diff --git a/.github/workflows/actions-ci.yml b/.github/workflows/actions-ci.yml
--- a/.github/workflows/actions-ci.yml
+++ b/.github/workflows/actions-ci.yml
@@ -41,8 +41,5 @@ jobs:
       - name: Build
         run: make
       - name: Check if built version is committed
-        run: git diff --quiet --exit-code
-      - uses: actions/github-script@v3
-        if: failure()
-        with:
-          script: core.setFailed('You forgot to build locally!')
+        run: |
+          git diff --quiet --exit-code || echo "::error::You forgot to commit the built actions" && exit 1
