Fi

diff --git a/.github/workflows/actions-ci.yml b/.github/workflows/actions-ci.yml
--- a/.github/workflows/actions-ci.yml
+++ b/.github/workflows/actions-ci.yml
@@ -42,4 +42,4 @@ jobs:
         run: make build
       - name: Check if built version is committed
         run: |
-          git diff --exit-code || echo "::error::You forgot to commit the built actions" && exit 1
+          git diff --quiet --exit-code || (echo "::error::You forgot to commit the built actions" && exit 1)
