Simplifiy workfllow

diff --git a/.github/workflows/edge-lambda-ci.yml b/.github/workflows/edge-lambda-ci.yml
--- a/.github/workflows/edge-lambda-ci.yml
+++ b/.github/workflows/edge-lambda-ci.yml
@@ -17,8 +17,8 @@ defaults:
     working-directory: edge-lambdas
 
 jobs:
-  test:
-    name: Test
+  ci:
+    name: Test & Build
     runs-on: [self-hosted, universal]
     permissions:
       contents: read
@@ -29,56 +29,27 @@ jobs:
           node-version: "16"
           cache: "yarn"
           cache-dependency-path: edge-lambdas/yarn.lock
-      - name: Install Dependencies
-        run: yarn --frozen-lockfile
-      - name: Run tests
-        run: make test
-
-  check-version:
-    name: Check Version
-    runs-on: [self-hosted, universal]
-    outputs:
-      upload_uri: ${{ steps.upload-uri.outputs.uri }}
-    permissions:
-      contents: read
-    steps:
-      - uses: actions/checkout@v2
       - uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-west-1
+      - name: Install Dependencies
+        run: yarn --frozen-lockfile
       - name: Get Upload URI
         id: upload-uri
         run: |
           echo "::set-output name=uri::s3://${{ env.S3_BUCKET }}/edge-lambdas/$(jq -r .version package.json)"
       - name: Check if version already exists
         run: |
-          (! aws s3 ls ${{ steps.upload-uri.outputs.uri}}) || (echo "::error::You forgot to update he version in package.json" && exit 1)
-
-  upload:
-    name: Build & Upload
-    runs-on: [self-hosted, universal]
-    needs: check-version
-    permissions:
-      contents: read
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v2
-        with:
-          node-version: "16"
-          cache: "yarn"
-          cache-dependency-path: edge-lambdas/yarn.lock
-      - uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-west-1
-      - name: Install Dependencies
-        run: yarn --frozen-lockfile
+          (! aws s3 ls ${{ steps.upload-uri.outputs.uri }}) || (echo "::error::You forgot to update he version in package.json" && exit 1)
+      - name: Run tests
+        run: make test
+      - name: Run Prettier
+        run: yarn prettier --check .
       - name: Build
         run: make
-      - name: Upload Files
+      - name: Upload Files to S3
         if: github.ref == 'refs/heads/main'
         run: |
-          aws s3 cp --recursive dist ${{ needs.check-version.outputs.upload_uri }}
+          aws s3 cp --recursive dist ${{ steps.upload-uri.outputs.uri }}
